### ISSUE TITLE
Unit of Scanner Bore Diameter

### ISSUE THREAD

**Issue by jhnnslschnr** [MagneticParticleImaging/OpenMPIData.jl#1]
The scanner bore diameter is stated to be 11.8 mm in the table [here](https://magneticparticleimaging.github.io/OpenMPIData.jl/latest/scanners.html), while i guess it should be 11.8 cm (like in the text above).

**Comment by tknopp** [comment]
thanks. Should be fixed by https://github.com/MagneticParticleImaging/OpenMPIData.jl/commit/f88279bfbc234ed32ede31bbcfd623f8a363fdb2

Will close once the documentation is build.

**Comment by jbeuke** [comment]
The same error is also in the text above the table.
